version: "3"
services:

  server:
    image: kongand/escala-server:latest
    ports:
      - 80:80
  
  php:
    image: php:7-fpm
    volumes:
      - ./:/escala

  composer:
    image: composer:latest
    volumes:
      - ./:/escala
    working_dir: /escala
    command: install